services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5429:5432"
    env_file:
      - .docker.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mdk

volumes:
  postgres_data:
networks:
  mdk: